<?php


//SYSTEM
define('SERVER_INTERNAL_ERROR',0);
define('SUCCESS',1);
define('ACTIVE',2);
define('IS_ADMIN',2);
define('IS_NOT_ADMIN',1);
define('CAPTCHA_ERROR',3);
define('LINK_EXPIRED',4);
define('URL_FORMAT_ERROR',5);

//FILE UPLOAD
define('FILE_OVERSIZE',4);
define('FILE_FORMAT_ERROR',5);

//ACCOUNT
define('ACCOUNT_DUPLICATED',1001);
define('ACCOUNT_INACTIVE',1002);
define('ACCOUNT_OR_PASSWORD_ERROR', 1003);
define('EMAIL_FORMAT_ERROR',1004);
define('ACCOUNT_NOT_EXIST',1005);


//CURSE_CATEGORY
define('CURSE_CATEGORY_NOT_EXIST',1006);